// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "HaRo87",
            "url": "https://github.com/HaRo87"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/HaRo87/dokerb/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/docs": {
            "get": {
                "description": "Get a list of helpful documentation resources",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "documentation"
                ],
                "summary": "Get the documentation info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apiserver.DocResponse"
                        }
                    }
                }
            }
        },
        "/sessions": {
            "post": {
                "description": "Creates a new Doker session and responds with the corresponding token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Create a new Doker session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apiserver.SessionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiserver.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{token}": {
            "delete": {
                "description": "Deletes a existing Doker session based on the provided token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Delete a existing Doker session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session Token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apiserver.GeneralResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiserver.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{token}/users": {
            "get": {
                "description": "Gets all users of an existing session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session",
                    "user"
                ],
                "summary": "Get the users of an existing session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session Token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apiserver.UsersResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiserver.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{token}/users/{name}": {
            "post": {
                "description": "Adds a new (non-existing) user to an existing session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session",
                    "user"
                ],
                "summary": "Add a new user to a existing session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session Token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Name of the user",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apiserver.GeneralResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiserver.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Removes a existing user from an existing session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session",
                    "user"
                ],
                "summary": "Remove a user from a session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session Token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Name of the user",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apiserver.GeneralResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiserver.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{token}/workpackages": {
            "get": {
                "description": "Gets all work packages of an existing session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session",
                    "workpackage"
                ],
                "summary": "Get the work packages of a session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session Token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apiserver.WorkPackagesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiserver.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Adds a new (non-existing) work package to an existing session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session",
                    "workpackage"
                ],
                "summary": "Add a new work package to a existing session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session Token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New Work Package",
                        "name": "workpackage",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apiserver.WorkPackage"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apiserver.GeneralResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apiserver.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiserver.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apiserver.DocEntry": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "format": "string",
                    "example": "GitHub"
                },
                "url": {
                    "type": "string",
                    "format": "string",
                    "example": "https://github.com/HaRo87"
                }
            }
        },
        "apiserver.DocResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "format": "string",
                    "example": "ok"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/apiserver.DocEntry"
                    }
                }
            }
        },
        "apiserver.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "format": "string",
                    "example": "error"
                },
                "reason": {
                    "type": "string",
                    "format": "string",
                    "example": "oops, something went wrong"
                }
            }
        },
        "apiserver.GeneralResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "format": "string",
                    "example": "ok"
                }
            }
        },
        "apiserver.SessionResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "format": "string",
                    "example": "ok"
                },
                "token": {
                    "type": "string",
                    "format": "string",
                    "example": "12345678901234567890123456789012"
                }
            }
        },
        "apiserver.UsersResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "format": "string",
                    "example": "ok"
                },
                "users": {
                    "type": "array",
                    "format": "[]string",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Tigger",
                        "Rabbit"
                    ]
                }
            }
        },
        "apiserver.WorkPackage": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "format": "string",
                    "example": "TEST01"
                },
                "summary": {
                    "type": "string",
                    "format": "string",
                    "example": "a sample task"
                }
            }
        },
        "apiserver.WorkPackagesResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "format": "string",
                    "example": "ok"
                },
                "workpackages": {
                    "type": "array",
                    "format": "[]datastore.WorkPackage",
                    "items": {
                        "$ref": "#/definitions/datastore.WorkPackage"
                    }
                }
            }
        },
        "datastore.WorkPackage": {
            "type": "object",
            "properties": {
                "effort": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "standardDeviation": {
                    "type": "number"
                },
                "summary": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.1.0",
	Host:        "localhost:5000",
	BasePath:    "/api",
	Schemes:     []string{},
	Title:       "Doker Backend API",
	Description: "A backend for playing Planning Poker with Delphi estimate method.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
